# Generated by Django 4.2.4 on 2024-09-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceReportTracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('companyName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customerEmail', models.TextField()),
                ('adsPlatform', models.TextField()),
                ('package', models.TextField()),
                ('catogery', models.TextField()),
            ],
        ),
    ]
