# Generated by Django 4.2.4 on 2024-09-02 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceReportTracking', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='performanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSubmission', models.TextField()),
                ('submittedReport', models.IntegerField(default=1000)),
                ('remark', models.TextField()),
                ('duration', models.TextField()),
                ('report', models.FileField(blank=True, null=True, upload_to='report/%Y')),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceReportTracking.customer')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceReportTracking.staff')),
            ],
        ),
    ]
