# Generated by Django 4.2.4 on 2024-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceReportTracking', '0004_customerplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerCatogery',
            fields=[
                ('katogeri', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
