# Generated by Django 4.2.4 on 2024-09-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceReportTracking', '0007_alter_customer_adsplatform_alter_customer_catogery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereport',
            name='dateSubmission',
            field=models.DateField(),
        ),
    ]
