# Generated by Django 4.2.4 on 2024-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceReportTracking', '0008_alter_performancereport_datesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('adminName', models.TextField()),
                ('adminPassword', models.TextField()),
                ('adminEmail', models.TextField()),
            ],
        ),
    ]
